### PR TITLE
Add some missing typing

### PR DESCRIPTION
**Pull request by Nauja**
* Add the type ItemType for subitems.
* Add the type MethodInfo for the tuple returned by get_method_info.
* Replace item.isMenu by isinstance(item, ContextMenu), isMenu is probably no longer required but I left it for compatibility.
* Fix some types
* Added missing Exception
* Ran black on the sources

Also drop support for Python3.6 as this is EOL and is missing support for some typing

### CODE REVIEW

**Comment by saleguas** [comment]
Awesome, thanks. I also sent an invite to be a contributor.

**Comment by Nauja** [comment]
> Awesome, thanks. I also sent an invite to be a contributor.

Hey thanks :)

For this PR I'm fighting with the Python3.6 version atm

**Comment by Nauja** [comment]
Are you sure you want to keep Python 3.6 as a supported version ? It has ended in 23 Dec 2021

**Comment by saleguas** [comment]
You can change the supported version. Truthfully, I haven't updated most of the code in a while because I've been really busy. I'm not sure of the current state of the ecosystem but I'll trust your judgment and look into it more

**Comment by Nauja** [comment]
> You can change the supported version. Truthfully, I haven't updated most of the code in a while because I've been really busy. I'm not sure of the current state of the ecosystem but I'll trust your judgment and look into it more

Well I was surprised you reacted so quickly :D

I think it's safe to say that Python3.6 can be dropped. It's not even part of the latest Ubuntu

**Comment by Nauja** [comment]
I added python_requires=">= 3.7", I think the PR is good now

**Comment by saleguas** [comment]
Merged and updated the pip package

**Pull request merged**
